# Archivo: gradle.properties
# Descripción: propiedades de compilación del proyecto Android PBIO.
# Copyright: 2026 Joan Catala Sendra (uso académico PBIO - UPV)
# Fecha: 2026-10-07
# Autor: Joan Catala Sendra
# Aportación: configuración mínima y reproducible del entorno Gradle.

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.nonTransitiveRClass=true
