// Archivo: settings.gradle
// Descripción: declaración de módulos y repositorios Gradle.
// Copyright: 2026 Joan Catala Sendra (uso académico PBIO - UPV)
// Fecha: 2026-10-07
// Autor: Joan Catala Sendra
// Aportación: configuración de módulos del proyecto Android.

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "PBIO-Sprint0-JoanCatala"
include ':app'
